# Generated by Django 5.0.2 on 2024-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo_identificativo',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
