# Generated by Django 5.0.2 on 2024-05-30 10:12

import django.db.models.deletion
import questions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosSocioDemograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(validators=[questions.models.validate_birth_date])),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('comunidad_autonoma', models.CharField(choices=[('Andalucía', 'Andalucía'), ('Aragón', 'Aragón'), ('Asturias', 'Asturias'), ('Baleares', 'Baleares'), ('Canarias', 'Canarias'), ('Cantabria', 'Cantabria'), ('Castilla-La Mancha', 'Castilla-La Mancha'), ('Castilla y León', 'Castilla y León'), ('Cataluña', 'Cataluña'), ('Extremadura', 'Extremadura'), ('Galicia', 'Galicia'), ('Madrid', 'Madrid'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('La Rioja', 'La Rioja'), ('País Vasco', 'País Vasco'), ('Valencia', 'Valencia'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
