# Generated by Django 5.0.2 on 2024-05-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoSjogren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_sjogren', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('anio_diagnostico', models.IntegerField(blank=True, choices=[(1, 'Hace 1 año'), (2, 'Hace 2 años'), (3, 'Hace 3 años'), (4, 'Hace 4 años'), (5, 'Hace más de 5 años')], null=True)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
