# Generated by Django 5.0.2 on 2024-05-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_diagnosticosjogren'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliautoinmunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_otras_enfermedades_autoinmunes', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('enfermedades_autoinmunes', models.CharField(blank=True, choices=[('Artritis reumatoide', 'Artritis reumatoide'), ('Enfermedad de Graves (tiroides)', 'Enfermedad de Graves (tiroides)'), ('Esclerosis múltiple', 'Esclerosis múltiple'), ('Lupus eritematoso', 'Lupus eritematoso'), ('Tiroiditis de Hashimoto (TH)', 'Tiroiditis de Hashimoto (TH)'), ('Otro', 'Otro')], max_length=50, null=True)),
                ('anio_diagnostico', models.IntegerField(blank=True, choices=[(1, 'Hace 1 año'), (2, 'Hace 2 años'), (3, 'Hace 3 años'), (4, 'Hace 4 años'), (5, 'Hace más de 5 años')], null=True)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
