# Generated by Django 5.0.2 on 2024-05-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_diagnosticosjogren_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliaresEnfermedadesAutoinmunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_familiares_enfermedades_autoinmunes', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
                ('grado_familiar', models.CharField(blank=True, choices=[('1', 'Padres, hijos'), ('2', 'Hermanos, abuelos, nietos'), ('3', 'Tíos, bisabuelos, biznietos, sobrinos'), ('4', 'Primos hermanos')], max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
