# Generated by Django 5.0.2 on 2024-05-30 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_antecedentesfamiliaresenfermedadesautoinmunes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AntecedentesFamiliaresEnfermedadesAutoinmunes',
            new_name='AntecedentesFamiliares',
        ),
    ]
