# Generated by Django 5.0.2 on 2024-05-30 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_antecedentesfamiliaresenfermedadesautoinmunes_antecedentesfamiliares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastrointestinal', models.BooleanField(default=False)),
                ('medicacion_gastrointestinal', models.TextField(blank=True, null=True)),
                ('renal', models.BooleanField(default=False)),
                ('medicacion_renal', models.TextField(blank=True, null=True)),
                ('dermatologico', models.BooleanField(default=False)),
                ('medicacion_dermatologico', models.TextField(blank=True, null=True)),
                ('neurologico', models.BooleanField(default=False)),
                ('medicacion_neurologico', models.TextField(blank=True, null=True)),
                ('endocrino', models.BooleanField(default=False)),
                ('medicacion_endocrino', models.TextField(blank=True, null=True)),
                ('hematologico', models.BooleanField(default=False)),
                ('medicacion_hematologico', models.TextField(blank=True, null=True)),
                ('musculo_esqueletico', models.BooleanField(default=False)),
                ('medicacion_musculo_esqueletico', models.TextField(blank=True, null=True)),
                ('cardiovascular', models.BooleanField(default=False)),
                ('medicacion_cardiovascular', models.TextField(blank=True, null=True)),
                ('pulmonar', models.BooleanField(default=False)),
                ('medicacion_pulmonar', models.TextField(blank=True, null=True)),
                ('cognitivo', models.BooleanField(default=False)),
                ('medicacion_cognitivo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
