# Generated by Django 5.0.2 on 2024-05-30 21:31

import django.db.models.deletion
import questions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_antecedentesmedicos_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_alergico_medicamento', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('tiene_otras_alergias', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('alergias_tipo', models.CharField(blank=True, choices=[('Alergia alimentaria', 'Alergia alimentaria'), ('Alergia a materiales', 'Alergia a materiales'), ('Alergia ambiental', 'Alergia ambiental'), ('Otra', 'Otra')], max_length=50, null=True)),
                ('otra_alergia', models.TextField(blank=True, null=True, validators=[questions.models.validate_not_blank])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
