# Generated by Django 5.0.2 on 2024-05-30 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alergias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_primera_menstruacion', models.IntegerField()),
                ('esta_embarazada', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('esta_usando_anticonceptivos', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('tiene_trastornos_menstruales', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('estado_menstrual', models.CharField(choices=[('Premenopausia', 'Premenopausia (periodos regulares)'), ('Perimenopausia', 'Perimenopausia/ transición menopáusica (cambios en los periodos)'), ('Postmenopausia', 'Postmenopausia (hace más de 12 meses que no tengo el periodo)')], max_length=50)),
                ('menopausia', models.CharField(blank=True, choices=[('Espontáneo', 'Espontáneo (“natural”)'), ('Quirúrgico', 'Quirúrgico (extirpación de ovarios)'), ('Quimioterapia', 'Quimioterapia o radioterapia'), ('Otro', 'Otro (explicar)')], max_length=50, null=True)),
                ('otra_menopausia', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_ultima_menstruacion', models.IntegerField(blank=True, null=True)),
                ('esta_usando_terapia_hormonal', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
