# Generated by Django 5.0.2 on 2024-05-30 22:02

import django.db.models.deletion
import questions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_estadomenstrual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitosNocivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualmente_fumas', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')])),
                ('cigarrillos_por_dia', models.IntegerField(blank=True, null=True)),
                ('edad_inicio_fumar', models.IntegerField(blank=True, null=True)),
                ('has_fumado_antes', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True)),
                ('cuando_comenzaste', models.CharField(blank=True, max_length=255, null=True, validators=[questions.models.validate_not_blank])),
                ('cigarrillos_por_dia_antes', models.IntegerField(blank=True, null=True)),
                ('cuando_dejaste', models.CharField(blank=True, max_length=255, null=True, validators=[questions.models.validate_not_blank])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
