# Generated by Django 5.0.2 on 2024-05-31 07:13

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_habitosnocivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomenstrual',
            name='edad_primera_menstruacion',
            field=models.IntegerField(validators=[questions.models.validate_range_0_120]),
        ),
        migrations.AlterField(
            model_name='estadomenstrual',
            name='edad_ultima_menstruacion',
            field=models.IntegerField(blank=True, null=True, validators=[questions.models.validate_range_0_120]),
        ),
        migrations.AlterField(
            model_name='estadomenstrual',
            name='otra_menopausia',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[questions.models.validate_not_blank]),
        ),
        migrations.AlterField(
            model_name='habitosnocivos',
            name='cigarrillos_por_dia',
            field=models.IntegerField(blank=True, null=True, validators=[questions.models.validate_range_0_200]),
        ),
        migrations.AlterField(
            model_name='habitosnocivos',
            name='cigarrillos_por_dia_antes',
            field=models.IntegerField(blank=True, null=True, validators=[questions.models.validate_range_0_200]),
        ),
        migrations.AlterField(
            model_name='habitosnocivos',
            name='edad_inicio_fumar',
            field=models.IntegerField(blank=True, null=True, validators=[questions.models.validate_range_0_120]),
        ),
    ]
