# Generated by Django 5.0.2 on 2024-06-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_alergias_alergias_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliautoinmunidad',
            name='otro_enfermedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
