# Generated by Django 5.0.2 on 2024-06-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_poliautoinmunidad_otro_enfermedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='encia',
        ),
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='extraoral',
        ),
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='labios',
        ),
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='lengua',
        ),
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='mucosa_yugal',
        ),
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='paladar',
        ),
        migrations.DeleteModel(
            name='Encia',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='encia',
            field=models.CharField(blank=True, choices=[('Derecha superior', 'Derecha superior'), ('Derecha inferior', 'Derecha inferior'), ('Izquierda superior', 'Izquierda superior'), ('Izquierda inferior', 'Izquierda inferior')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Extraoral',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='extraoral',
            field=models.CharField(blank=True, choices=[('Extraoral', 'Extraoral')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Labios',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='labios',
            field=models.CharField(blank=True, choices=[('Superior cara externa', 'Superior cara externa'), ('Superior cara interna', 'Superior cara interna'), ('Inferior cara externa', 'Inferior cara externa'), ('Inferior cara interna', 'Inferior cara interna'), ('Comisura', 'Comisura')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Lengua',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='lengua',
            field=models.CharField(blank=True, choices=[('Dorso', 'Dorso'), ('Borde lateral derecho', 'Borde lateral derecho'), ('Borde lateral izquierdo', 'Borde lateral izquierdo'), ('Punta', 'Punta'), ('Vientre', 'Vientre')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='MucosaYugal',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='mucosa_yugal',
            field=models.CharField(blank=True, choices=[('Derecha', 'Derecha'), ('Izquierda', 'Izquierda'), ('Ambas', 'Ambas')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Paladar',
        ),
        migrations.AddField(
            model_name='sindromebocaardiente',
            name='paladar',
            field=models.CharField(blank=True, choices=[('Paladar', 'Paladar')], max_length=50, null=True),
        ),
    ]
