# Generated by Django 5.0.2 on 2024-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_remove_sindromebocaardiente_encia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='comer_beber',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='disfrutar_relaciones_sociales',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='dormir_relajarse',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='estado_emocional',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='hablar',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='higiene_dental',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='mostrar_sonrisa',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='realizar_trabajo_habitual',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
    ]
