# Generated by Django 5.0.2 on 2024-06-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_alter_sindromebocaardiente_comer_beber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='alteraciones_gusto',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='atribucion_sintomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='comer_beber',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='cuerpo_extraño_boca',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='disfrutar_relaciones_sociales',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='dormir_relajarse',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='estado_emocional',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='factor_desencadenante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='hablar',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='halitosis',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='higiene_dental',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='intolerancia_protesis',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='mostrar_sonrisa',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='realizar_trabajo_habitual',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], default='Sin dificultad', max_length=20),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='sintomas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='tiene_sintomas',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='tipo_alteracion_gusto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='ulceraciones_boca',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
    ]
