# Generated by Django 5.0.2 on 2024-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_sindromebocaardiente_alteraciones_gusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='alteraciones_gusto',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='comer_beber',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='cuerpo_extraño_boca',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='disfrutar_relaciones_sociales',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='dormir_relajarse',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='estado_emocional',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='hablar',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='halitosis',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='higiene_dental',
            field=models.CharField(choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='intolerancia_protesis',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='mostrar_sonrisa',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='realizar_trabajo_habitual',
            field=models.CharField(blank=True, choices=[('Sin dificultad', 'Sin dificultad'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave'), ('Incapacitante', 'Incapacitante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='ulceraciones_boca',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
    ]
