# Generated by Django 5.0.2 on 2024-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_sindromebocaardiente_alteraciones_gusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sindromebocaardiente',
            name='halitosis',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
    ]
