# Generated by Django 5.0.2 on 2024-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_sindromebocaardiente_halitosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sindromebocaardiente',
            name='calidad_vida',
        ),
    ]
